### ISSUE TITLE
Inverted variables in example

### ISSUE THREAD

**Issue by anuraagvaidya** [Alendorff/fuzzyIS#1]
In the code example, the service is defined as gauss and food is defined as trapezoid, but the labeled graphs are inverted? i.e. the graph of the service is trapezoidal and the graph of food is gaussian.

**Comment by maksnester** [comment]
Yes, thank you, I placed pics in wrong order. Fixed it.

> ![image](https://user-images.githubusercontent.com/4989157/28671742-08aed016-72de-11e7-80dc-df8a3fc7c3db.png)
