### ISSUE TITLE
Code Syntax Issue

### ISSUE THREAD

**Issue by chixsy** [Alendorff/fuzzyIS#2]
Hello Alendorff,

Thanks for the tutorial, but I noticed some issues while trying your code. 

A syntax issue in this codeblock - parantheses/semi-colon prevents the code from running.
Fixing the obvious errors leads to another set of Type errors.
TypeError: system.addOutputs is not a function.

----------------
let outputs = [
    system.addOutputs(new LV('service', [0, 30]);
];
----------------

**Comment by maksnester** [comment]
Thank you for your feedback, I've updated the readme and added complete code for the example in readme. Hope it will help.
